### PR TITLE
Was wondering if I could make some pull requests...

### PR DESCRIPTION
**Pull request by 0b1kn00b**
Looking to deprecate stax.

### CODE REVIEW

**Comment by fponticelli** [comment]
You are very welcome to make PR. The only change I would make is to type the `Array` arguments as `thx.ReadonlyArray` since these methods are not going to mutate them.

**Comment by 0b1kn00b** [comment]
Updated and a few additions.

**Comment by fponticelli** [comment]
Thank you! I think return types should be `Array` but I will make that change myself. No reason to put this on hold any longer.

**Comment by fponticelli** [comment]
Actually I misread this. I am fine to have the methods in `thx.Arrays` but they should take `ReadonlyArray` and return `Array`. That way the methods will be compatible with both `Array` and `ReadonlyArray` but you can decide the immutable way and adopt the latter.

**Comment by 0b1kn00b** [comment]
Ok, that ok?

**Comment by fponticelli** [comment]
thank you!

**Pull request merged**
