### PR TITLE
Method aliases for disambiguation

### PR DESCRIPTION
**Pull request by TiZ-EX1**
This pull request creates aliases for the parse methods in Ints, Int64s, and Float. When using mega Thx, trying to call parse on a string returns a Url. With this, intent is clearer.

In addition, there's an alias for Ints.toString, toBase. When using mega Thx, it attempts to call standard toString, and I get a too many args error. I would argue for actually renaming toString to toBase, but with the alias, existing code that might be using it doesn't break.

### CODE REVIEW

**Comment by TiZ-EX1** [comment]
Oh, bluh. I wanted to work on some more stuff to get added into Thx, I should have made a branch. Oh well, hopefully the branches I make won't depend on these changes. :|

**Comment by TiZ-EX1** [comment]
I'm gonna cancel this pull request so I can make a branch. Sorry for the trouble. :(

**Comment by TiZ-EX1** [comment]
Ffff, never mind. I can't move those commits onto a branch now that I've pushed them. I'm bad at git. :( I'm sorry for the trouble, man.

**Comment by TiZ-EX1** [comment]
It looks like Asserts.contains clashes with Arrays.contains too. I could create an alias for Arrays.contains, but I feel like either Asserts should just not be in mega Thx, or its functions should be renamed.

**Comment by fponticelli** [comment]
I am ready to merge this PR. One question first. What if we move `Assert` at the top of the list? That should prioritize `Arrays.contains` and others over `Assert` methods.

**Comment by TiZ-EX1** [comment]
I'd be fine with that. I updated the PR. ...Also, lol, didn't actually kill the blank line in Thx.hx like the commit says it did. I am such a dingus. >.<

**Comment by fponticelli** [comment]
Thank you very much for the contributions. They really are appreciated. Just waiting for the build to succeed before the official merge.

**Comment by TiZ-EX1** [comment]
I'm really happy to help! ^.^

**Pull request merged**
