### PR TITLE
Arrays.splitByPad(n, e) pads a splitBy(n) array's last group with e if necessary

### PR DESCRIPTION
**Pull request by TiZ-EX1**
I made use of this for one of my /r/DailyProgrammer challenges when I was still primarily using JS; it was a nifty function that was part of Sugar.JS.

In addition, there is groupsOfPad(n, e) that pads the last group with element e until it has n elements, if necessary.

Includes the commits in my alias pull request because I'm bad at git. Sorry. :(

### CODE REVIEW

**Comment by fponticelli** [comment]
Isn't `Arrays.groupsOf` the same as `Arrays.split`?

**Comment by TiZ-EX1** [comment]
You're absolutely right. (It's the same as splitBy, but the important thing is that it is already there.)

How should we proceed from here, then? It looks like groupByPad doesn't have an equivalent function. Should I just change groupByPad into splitByPad and then make it use splitBy?

**Comment by TiZ-EX1** [comment]
I went ahead and did that. :)

**Comment by fponticelli** [comment]
Sounds good to me ;)

**Comment by TiZ-EX1** [comment]
Awesome. Thanks, man. :)

**Pull request merged**
