### PR TITLE
Lambda lambda lambda

### PR DESCRIPTION
**Pull request by francescoagati**
Hi,
this a pull request for merge some of the function of lib funcgen (functions short lambda and forms inspired to lisp).
i have create the namespace thx.macros.lambda for add Functions and Forms.
and add to macro a function replaceSymbol for symbols manipulation.

An example of shortlambdas and forms

```
import thx.macro.lambda.Functions.*;
import thx.macro.lambda.Forms.*;

class TestLambda {
  public function new() { }

  public function testFunctions() {
    Assert.same([2,3], [1,2].map(fn(_+1)));
    Assert.equals(0, fn0((0))());
    Assert.equals(2, fn1((_1))(2));
    Assert.equals(3, fn2(_1+_2)(1,2));
    Assert.equals(6, fn3(_1+_2+_3)(1,2,3));
    Assert.equals(10, fn4(_1+_2+_3+_4)(1,2,3,4));
    Assert.equals(15, fn5(_1+_2+_3+_4+_5)(1,2,3,4,5));
    Assert.equals(6, fn5(_1+_2+_3)(1,2,3,4,5));
  }

  public function testForms() {
    with(Assert,{
      _.equals(1,1);

      var check1 = 0;
      when(1==1,{
        _.equals(1,1);
        check1 = 1;
      });
      _.equals(check1,1);

      var check2 = 0;
      unless(1==1,{
        _.equals(1,1);
        check2 = 1;
      });
      _.equals(check2,0);

      var check3 = 0;
      unless(1!=1,{
        _.equals(1,1);
        check3 = 1;
      });
      _.equals(check3,1);

      var check5 = 0;
      when(and(1==1,2==2),{
        _.equals(1,1);
        check5 = 1;
      });
      _.equals(check5,1);

      var check6 = 0;
      when(or(1==2,2==2),{
        _.equals(1,1);
        check6 = 1;
      });
      _.equals(check6,1);

      _.equals(false,not(true));
      _.equals(true,not(false));
      
    });

```

### CODE REVIEW

**Comment by fponticelli** [comment]
A few considerations:

  - in `fnX` can't the macro itself figure out the number of required arguments by checking the highest of the _X variables?
  - for `fn0` can't we use just the `_` without a number? (that applies to point 1 as well)
  - for consistency with `thx.Tuple` can we start the sequencing at `0`? If you have a strong opinion about this we can review tuple to have `_1`/`_2` instead of `_0`/`_1`.
  - the features should be more easily accessible and possibly directly from `thx.Functions` (the implementation on the other hand could be very well kept in `thx.core.lambda.Functions` as you did already). Maybe the `thx.Functions` could count the arguments and delegate to the right `fnX`.
  - `Forms` ... I like the examples a lot and I am going to use it for sure! The only concern I have is the name `Forms` itself :) It is a name used for many things and this is the last I would think about. Probably it is just me but do we have alternatives? An option could be to make it part of `thx.Functions` (not a perfect fit probably) and again keep the implementation where it is now.

  Great work!

**Comment by ponticelli** [comment]
What about `thx.macro.lambda.Forms` becomes `thx.Conditions`?

**Comment by fponticelli** [comment]
What about thx.macro.lambda.Forms becomes thx.Conditions?

**Comment by francescoagati** [comment]
Thanks Franco.
My Proposal:
-  for fnX i think that is better to use statical versions instead of calculate the highest because short lambda can be used many times and extends the compilation time
- fn0 is a function without parameters as Void->Dynamic i dont' know if is better a version with Void->Void
- yes we can start from 0
- I thinks that we could only use Functions 
so we could have:
-   thx.Functions.fn
-   thx.Functions.with
-   thx.Functions.Function0.fn0
-   thx.Functions.Function1.fn1
-   thx.Functions.Function2.fn2
-   thx.Functions.Function3.fn3
-   thx.Functions.Function4.fn4
-   thx.Functions.Function5.fn5
-   thx.Functions.Conditions.when
-   thx.Functions.Conditions.unless
-   thx.Functions.Conditions.and
-   thx.Functions.Conditions.or
-   thx.Functions.Conditions.not

**Comment by fponticelli** [comment]
Are you sure the additional cost for calculating the arguments is really impacting? I mean there is a penalty for sure but is it measurable? The convenience of adding arguments without changing signature seems considerable. `fn0` should be of type `Void->T` and let the compiler infer the right type. Same for the other combos.

**Comment by francescoagati** [comment]
yes you are right. i try to modify fn with calculate the arguments.

**Comment by fponticelli** [comment]
thanks!

Il giorno mar 2 giu 2015 alle ore 12:57 francesco agati <
notifications@github.com> ha scritto:

**Comment by fponticelli** [comment]
what is the advantage of this:
```
macro public static function fn(filter:Expr) {
  var new_filter = filter.map(replace_());
  return macro function(__tmp1) { return $new_filter;  };
}
```

over 

```
macro public static function fn(ex:Expr) {
  return macro function(_) { return $e{e}  };
}
```

?

**Comment by francescoagati** [comment]
yes in effect i have write this code much faster for see how can be used. After the works on fn arguments i will do a clean up.

I don't know if symbol _ can go in conflict with _ used in bind and switch.
In other language are used other symbols. Groovy and Livescript use "it" but also it can go in conflict with for example jasmine test in javascript.

for params counter livescript use &0,&1 and clojure %0,%1

**Comment by francescoagati** [comment]
Last Changes
moving namespaces from thx.macro.lambda to thx.Functions
```
import thx.Functions.fn;
import thx.Functions.with;
import thx.Functions.Functions0.fn0;
import thx.Functions.Functions1.fn1;
import thx.Functions.Functions2.fn2;
import thx.Functions.Functions3.fn3;
import thx.Functions.Conditions.*;
```
fn now can dispatch on different function signature depending from the highest param

```
    Assert.equals(1, fn(Std.parseInt(_0))("1"));
    Assert.equals(1, fn(Std.parseInt(_))("1"));
    Assert.equals(1, fn(_0)(1));
    Assert.equals(3, fn(_0+_1)(1,2));
    Assert.equals(6, fn(_0+_1+_2)(1,2,3));
    Assert.equals(10, fn(_0+_1+_2+_3)(1,2,3,4));
    Assert.equals(15, fn(_0+_1+_2+_3+_4)(1,2,3,4,5));
``` 
with fn params can't be optional
this fail
```
    Assert.equals(15, fn(_0+_1+_2+_3+_4)(1,2,3));
```
_  is an alias for _0
```
    Assert.equals(1, fn(_)(1));
    Assert.equals(3, fn(_+_1)(1,2));
    Assert.equals(6, fn(_+_1+_2)(1,2,3));
    Assert.equals(10, fn(_+_1+_2+_3)(1,2,3,4));
    Assert.equals(15, fn(_+_1+_2+_3+_4)(1,2,3,4,5));

```

**Comment by fponticelli** [comment]
it seems to require a lot of imports what if `fnX` goes in `Functions` directly and Conditions goes to `thx.Conditions`? That would require 2 imports:

```
import thx.Functions.*;
import thx.Conditions.*;
```

**Comment by francescoagati** [comment]
Do it.
now use only 
```
import thx.Functions.*;
import thx.Conditions.*;
```

**Comment by fponticelli** [comment]
Awesome, let's wait for the build and then I will merge ... thank you very much!

**Comment by francescoagati** [comment]
ok. thanks to you for the feedbacks.

**Comment by fponticelli** [comment]
Yay, I will try to make a release ASAP.

**Comment by francescoagati** [comment]
good thanks :-)

**Pull request merged**
